sonar.projectKey=lazaro-contato_pos-fiap-oficina-mecanica
sonar.projectName=pos-fiap-oficina-mecanica
sonar.sourceEncoding=UTF-8

sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/**
